### ISSUE TITLE
Starting with 1.2.5 alsactl tries to initialize UCM even if it is not supported

### ISSUE THREAD

**Issue by nmeum** [alsa-project/alsa-utils#101]
Starting with alsa-utils 1.2.5 I observed the following warning on my machine when running `alsactl restore 0`, which I didn't receive prevously with alsa-utils 1.2.4:

```
$ alsactl -E 'HOME=/var/run/alsasound' -I -f /var/lib/alsa/asound.state restore 0
alsa-lib parser.c:2372:(load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf'.
alsa-lib main.c:1405:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
```

The error message tells me that alsa-utils 1.2.5 now tries to initialize UCM by default which doesn't work since I don't have [alsa-ucm-conf](https://github.com/alsa-project/alsa-ucm-conf) installed. After installing alsa-ucm-conf, the error message looks as follows:

```
$ alsactl -E 'HOME=/var/run/alsasound' -I -f /var/lib/alsa/asound.state restore 0
alsa-lib parser.c:242:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0xf2530000 irq 35)
alsa-lib main.c:1405:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
```

From reading the alsactl man page, it seems to me that UCM should only be initialized by default if it is available. Since alsactl 1.2.4 did not attempt to initialize UCM on my machine, this seems to be a regression introduced in alsactl 1.2.5. If I disable UCM explicitly using `alsactl -U`, everything works as expected. Similarly, downgrading to alsactl 1.2.4 again also resolves the issue.

I am not familiar at all with alsa internals but if desired, I can check with `git-bisect(1)` which commit between `v1.2.4..v1.2.5` introduced this regression.

**Comment by nmeum** [comment]
> I can check with `git-bisect(1)` which commit between `v1.2.4..v1.2.5` introduced this regression.

`git-bisect start v1.2.5 v1.2.4` tells me that 9a2115b5ccb53b0224bdc3bc965c1e6de7e82a2d (CC: @perexg) is the first bad commit.

**Comment by perexg** [comment]
UCM is used all time now even if the configuration is not present or partial (second case / error). The error is harmless for the legacy hardware. It's a dup of #159.
