### ISSUE TITLE
system stops working, depends on alsa-sink-ALC283

### ISSUE THREAD

**Issue by supervisitor** [alsa-project/alsa-utils#102]
the system stops working, the disk is continues running... sometimes after 1-2 hours... the system comes back, full working after more than 8 hours...
what I was doing: it is always after looking some hours streaming movies with firefox

the alsa-info output is here:
[http://alsa-project.org/db/?f=c02c95149f023eeb6db51e5c528d8890609f4ae8](http://alsa-project.org/db/?f=c02c95149f023eeb6db51e5c528d8890609f4ae8)

the syslog shows this:
```
Jul  7 15:30:29 MyCompi pulseaudio[1892]: E: [alsa-sink-ALC283 Analog] alsa-util.c: snd_pcm_avail() gibt einen Wert zurück, welche außerordentlich groß ist: 4216608 bytes (21961 ms).
Jul  7 15:30:49 MyCompi pulseaudio[1892]: E: [alsa-sink-ALC283 Analog] alsa-util.c: Dies ist wahrscheinlich ein Fehler im ALSA-Treiber 'snd_hda_intel'. Bitte melden Sie diesen Punkt den ALSA-Entwicklern.
Jul  7 15:31:26 MyCompi pulseaudio[1892]: E: [alsa-sink-ALC283 Analog] alsa-util.c: snd_pcm_dump():
```

**Comment by perexg** [comment]
It's just a consequence that the system is busy and the audio does not run in realtime. Try to trace why your system is busy (what task occupies CPU).

**Comment by supervisitor** [comment]
Are you sure? I am looking for the reason why the computer hangs for no reason.
On the computer only the browser is open and shows only one page with a live stream. Then after a few hours the computer stops (no input works, no screen changes) and the disk does not stop... massive I/O.
This was the only thing I found so far.... otherwise there is nothing about a problem in the systemlog and firefox doesn't say anything more about the issue.
iotop shows a task from FF that stresses the disk... but I'm still looking for the trigger.

**Comment by perexg** [comment]
If the system is slow, then the sound malfunction, because the pulseaudio task has not enough CPU time. But it does not mean that the sound subsystem causes this problem. There are several methods, how to profile (measure the time spend in) the kernel, but it's out of scope of this project.
