### ISSUE TITLE
Filtering/manipulating MIDI messages

### ISSUE THREAD

**Issue by neilbags** [alsa-project/alsa-utils#106]
Hi, I'm using aconnect to send MIDI data from one USB MIDI device to another.

I need to filter the messages, so that only one MIDI channel gets sent through, or ideally, send data that comes in on one channel from device A out to device B on a different MIDI channel.

Is there any way to do this just with the command line tools?

**Comment by folkertvanheusden** [comment]
Maybe [midish](https://midish.org/)?

**Comment by neilbags** [comment]
Update: got what I needed working with qmidiroute (not command line). Had a quick go at doing the same in midish but no joy yet. Looks like it should be possible, I think I'm missing a command somewhere
