### ISSUE TITLE
Typo in alsamixer(1) manpage

### ISSUE THREAD

**Issue by climbTheStairs** [alsa-project/alsa-utils#110]
In the second paragraph of the "MIXER VIEWS" section, it says...

> The currently selected item is drawn in red and/of emphasized.

...when it should say...

> The currently selected item is drawn in red **and/or** emphasized.

**Comment by perexg** [comment]
Thank you for your report. Fixed in https://github.com/alsa-project/alsa-utils/commit/c4e43384fc8af468900b6771a23bdf44d03347a5 .
