### ISSUE TITLE
include a sample `alsamixer.rc` file?

### ISSUE THREAD

**Issue by int-e** [alsa-project/alsa-utils#112]
I think it would be useful to include an example `alsamixer.rc` file; see https://gist.github.com/int-e/25bd77d4e59531fad7d48bfaf1fc1046 for a candidate.

In particular this example replicates the default color theme, making it easier to adjust (say, replace `default` by `black` to get sane colors back in terminals with bright backgrounds). The default keybindings are also replicated but that's probably less useful.

**Comment by bharatvaj** [comment]
Thanks @int-e .  The man page for alsamixer has commands with '_' in between them in the COMMAND section. I was trying something like `bind q mixer_close` like mentioned in  the man page which didn't work and it was really confusing. After some googling found this issue and `bind q mixer close` worked. Having an example alsamixer.rc will be really useful. Or atleast having an EXAMPLES section in the man page would be helpful for new users like me.

**Comment by perexg** [comment]
Thanks. I added this file to the repository.
