### ISSUE TITLE
Scripts to save and reload ALSA settings on shutdown/reboot doesn't work for Baytrail atom

### ISSUE THREAD

**Issue by Pic-master** [alsa-project/alsa-utils#113]
Issue persists across various distributions.  
"best" workaround I've found is to save a copy of asound.state to user home directory, and run alsactl --file /home/asound.state restore at boot.  Janky work around that only works for one user.  Chased the issue as far as I could.
Running sudo alsactl restore also works, but must be done after each reboot (also had to manually "sudo alsactl store" first)

Currently on GalliumOS 3.0
Acer CB-131 N15Q10

**Comment by Pic-master** [comment]
/etc/rcS.d/S01alsa-utils

**Comment by Pic-master** [comment]
[alsa-utils.zip](https://github.com/alsa-project/alsa-utils/files/7270703/alsa-utils.zip)

**Comment by perexg** [comment]
I think that the card may not be available at boot, because it loads the firmware and it may take some time. Use udev rules to resolve this issue like: https://github.com/alsa-project/alsa-utils/blob/master/alsactl/90-alsa-restore.rules.in (the final rules file is available after make)

**Comment by Pic-master** [comment]
That may be the issue, however 90-alsa-restore.rules is currently in /lib/udev/rules.d, and I've tried copying it to /etc/udev/rules.d and it still fails to restore settings
[90-alsa-restore.rules.zip](https://github.com/alsa-project/alsa-utils/files/7281702/90-alsa-restore.rules.zip)
alsamixer does show two sound cards, one for the HDMI and another for the sound card.

**Comment by Pic-master** [comment]
Found this as well; 
`travis@galliumos:~$ sudo service alsa-restore status
● alsa-restore.service - Save/Restore Sound Card State
   Loaded: loaded (/lib/systemd/system/alsa-restore.service; static; vendor pres
   Active: inactive (dead)
Condition: start condition failed at Mon 2021-10-04 18:44:17 EDT; 7min ago
           └─ ConditionPathExistsGlob=/dev/snd/control* was not met
     Docs: man:alsactl(1)
lines 1-6/6 (END)
` 
I have two files in /dev/snd/ ControlC0 and ControlC1

**Comment by perexg** [comment]
`ConditionPathExistsGlob=` line is not in the https://github.com/alsa-project/alsa-utils/blob/master/alsactl/90-alsa-restore.rules.in file. It seems like a distribution specific extension.
