### ISSUE TITLE
wrong test in alsa-info.sh

### ISSUE THREAD

**Issue by mhampl** [alsa-project/alsa-utils#115]
In line 691 of alsa_info.sh script (version 0.5.0) a test for $TEMPDIR/alsa-usbstream.tmp is needed instead of $TEMPDIR/lsusb.tmp

**Comment by mhampl** [comment]
> In line 691 of alsa_info.sh script (version 0.5.0) a test for $TEMPDIR/alsa-usbstream.tmp is needed instead of $TEMPDIR/lsusb.tmp

Sorry, wrong line number, must of course be line 701 that needs the change.

**Comment by perexg** [comment]
Thank you for your report. Fixed in https://github.com/alsa-project/alsa-utils/commit/c6a9e53ca064074273f5c9ef73213fd3ec0c8e0e .
