### ISSUE TITLE
AM_PATH_ALSA. error

### ISSUE THREAD

**Issue by steeley** [alsa-project/alsa-utils#116]
Hi,
I'm installing on latest raspios buster lite 32bit:
(Linux cm432 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux)

my build process is:

`git clone https://github.com/alsa-project/alsa-utils.git
cd alsa-utils/
git checkout v1.1.9
autoreconf -i
./configure --prefix=/usr/local
make
sudo make install`

I have built and installed alsa-libs, and alsa-plugins  correctly, but get this error with alsa-utils when I autoreconf:

`configure.ac:22: warning: macro 'AM_PATH_ALSA' not found in library
configure.ac:22: error: possibly undefined macro: AM_PATH_ALSA
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1`

How to resolve?
TIA

**Comment by marc-hb** [comment]
If you're getting this error while trying to install locally, take a look at #272. At the very least it will have some clues.
