### ISSUE TITLE
Need info: How can I have conditional includes in a topology conf file

### ISSUE THREAD

**Issue by ranj063** [alsa-project/alsa-utils#118]
For example: I want to be able to conditionally include the DMIC pipelines/DAI's depending on whether the device has DMICs or not.

**Comment by ranj063** [comment]
@perexg is it possible to use variables as in UCM2 and regex to perform conditional includes in alsautils as well?

**Comment by perexg** [comment]
There's no such feature for the standard alsa-lib configuration parser. The dynamic configuration is handled differently for the device definitions (`snd_config_search` / `snd_config_expand`) and the UCM has own conditional mechanism (see `ucm_cond.c`).

I would probably suggest to implement this in the new way for the topology files according the specific requirements.

**Comment by perexg** [comment]
I see that you're using `snd_config_expand` in https://github.com/alsa-project/alsa-utils/pull/117 .

In this case, the load hooks can be used - see the `alsa.conf` for an example (at the begin of this file). But the conditionals are not supported. The included configuration file may be created from the environment variable or so.

**Comment by ranj063** [comment]
@perexg thank for the hint about hooks. So would it be OK to do something like this for ex:
```
@hooks [
	{
		func load
		files [
			{
				@func getenv
					vars [
						DMIC_CONF
					]
					default ""
				}
			}
		]
		errors false
	}
]
```

and I could set the DMIC_CONF env variable at build time based on which config I'm building for?

And I'd still need the PR #117 to set some values in the generated topology based on input arguments.

**Comment by ranj063** [comment]
@perexg it looks like the snd_config_search_hooks() is not exposed in the conf.h. Would it OK to expose it?

**Comment by ranj063** [comment]
@perexg I thought about this a bit more and I think it would be helpful if we implemented conditional includes in topology to suit our needs in the topology pre-processor in alsatplg. I was thinking of the following syntax:
```
Include."dmic" {
	argument [
		DMIC_CH_COUNT
	]
	values [
		"0"
		"2"
		"4"
	]
	includes [
		""
		"dmic-generic-2ch.conf"
		"dmic-generic-4ch.conf"
	]
}
```
Which can be used to pick the right conf to include depending on the argument value provided for DMIC_CH_COUNT. 

This will also allow nesting multiple nested conditional includes and we can expand the includes as the first pass of the pre-processor after expanding the arguments before compilation. For example in dmic-generic-2ch.conf could have something like:
```
Include."dmic_quality" {
	argument [
		DMIC_QUALITY
	]
	values [
		"low-quality"
		"high-quality"
	]
	includes [
		"dmic-low-quality.conf"
		"dmic-high-quality.conf"
	]
}
```

Please let me know what you think of this.

**Comment by perexg** [comment]
It looks like a simple configuration file stacking. Perhaps, it may be enough to handle multiple merged configuration files together and set the list in the caller (Makefile or so) ? Look for `snd_config_merge()` function to merge two trees in memory.

**Comment by ranj063** [comment]
But its a bit more than stacking too. The main issue for me is including the new conf at the right node:
For ex: the coeff for eqiir as below
```
Object.Widget.eqiir.1 {
    Object.Control.bytes.1 {
        name eqiir_bytes_4
        # include coeff for the EQIIR
    }
}
```

**Comment by perexg** [comment]
I see. It seems like the simple way:

```
IncludeByKey.DMIC_QUALITY.low "dmic-quality-low.conf"
IncludeByKey.DMIC_QUALITY.high "dmic-quality-high.conf"

# or

IncludeByKey.DMIC_QUALITY {
  low "dmic-quality-low.conf"
  high "dmic-quality-low.conf"
}

```

Eventually, the keys may be matched using regex.

**Comment by ranj063** [comment]
That could work. Let me circle back with my team and check if that works for our requirements. Thanks @perexg

**Comment by ranj063** [comment]
@perexg whie I am at this, could you please also give me some advice on how to deal with evaluating expressions such as 
"LINK_ID * 256 + 2" in a conf node. For Soundwire machines, we'd like to use the same input topology conf file but modify the DAI ID based on the LINK_ID value passed at build time. For ex:

```
Object.Dai.Soundwire.1 {
     ID    "LINK_ID * 256 + 2"
}
```
Can I use a library for evaluating math expressions? And if so, how would I specify that the node value should be evaluated? Thanks for your help!
