### ISSUE TITLE
Shouldn't there be an error..

### ISSUE THREAD

**Issue by auwsom** [alsa-project/alsa-utils#121]
..when I type `aplay test.wav` and there is "no soundcards found" when I type `aplay -l`? Instead of nothing. How would I know to check if there is a soundcard, versus some other component of was causing no sound to be heard. Thanks

**Comment by perexg** [comment]
It depends what you want to test. The sysfs (`/sys/class/sound/`) or procfs (`/proc/asound/`) may be used for a quick lookup without any ALSA tools. Or just check for the return code from aplay or amixer:

```
$ aplay -D hw:6 /dev/zero
ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for 6
aplay: main:830: audio open error: No such file or directory
$ echo $?
1

$ aplay -D hw:4 -f dat /dev/zero
Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
$ echo $?
0

$ amixer -D hw:4 info
Card hw:4 'Loopback'/'Loopback 1'
  Mixer name	: 'Loopback Mixer'
  Components	: ''
  Controls      : 98
  Simple ctrls  : 2
$ echo $?
0

$ amixer -D hw:6 info
ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for 6
amixer: Control device hw:6 open error: No such file or directory
$ echo $?
1
```

**Comment by auwsom** [comment]
@perexg So I guess you don't understand what I'm saying, or just disagree with it. 

As I said, I know I can explicitly check. And I know there are system methods, and pulseaudio methods. However, because alsa is needed by pulseaudio and is default on Ubuntu, and has some popular troubleshooting utilities like aplay and arecord, it is often recommended to check it on many forums before pulseaudio. 

Anyway, I don't know how to convince you that running aplay with a test audio file should give an error message (like nearly every other Linux utility) instead of fail silently, if you don't think that is obvious. I'm sure its trivial to code. So I'll leave it to others also trying to help alsa live up to common linux standards and end up either here or filing their own GitHub issue to add their weight. 

Outside of opinion, is there a logical reason why you don't think alsa should have an error message when failing at one of it's primary purposes as far as direct user interaction is concerned?

**Comment by perexg** [comment]
> @perexg So I guess you don't understand what I'm saying, or just disagree with it.
> 
> As I said, I know I can explicitly check. And I know there are system methods, and pulseaudio methods. However, because alsa is needed by pulseaudio and is default on Ubuntu, and has some popular troubleshooting utilities like aplay and arecord, it is often recommended to check it on many forums before pulseaudio. And there are droves of user who check this first and get no helpful information.
> 
> Anyway, I don't know how to convince you that running aplay with a test audio file should give an error message (like nearly every other Linux utility) instead of failling silently, if you don't think that is obvious. I'm sure its trivial to code. So I'll leave it to others also trying to help alsa live up to common linux standards and end up either here or filing their own GitHub issue to add their weight.
> 
> Outside of opinion, is there a logical reason why you don't think alsa should have an error message when failing at one of it's primary purposes as far as direct user interaction is concerned?

The original question was not very accurate. I follow you now. The aplay should give an error if there is no valid output. But if you use pulseaudio plugin (as you see - the distribution decided to redirect the standard PCM playback to pulseaudio), the pulseaudio is resposible to route the PCM stream to the correct output. You are probably talking about the case where there are no ALSA soundcards, but pulseaudio is running. Pulseaudio installs the dummy driver in this case by default. So, it's definitely not responsibility of the aplay utility (which does know nothing about the pulseaudio redirection) to handle this case. You should configure pulseaudio to not start with the dummy driver, if you don't like that. It's just a black hole, but everything seems like working.

**Comment by auwsom** [comment]
@perexg Great, thanks that helps. I didn't know about the dummy sink.

Still, don't you think if I use `aplay test.wav` (and it plays whether or not pulseaudio is running - usually a problem when running as root) and it doesn't play (again I've had the soundcard show present on root but not on a user shell with `aplay -l`), shouldn't it complain or inform there is no soundcard? (One of my issues was using a server kernel that didnt have the audio module, or sometimes with a newly created user that hadnt been added to the audio group). 

Forgive me if I'm not understanding what youre saying about the dummy sink. From my perspective it seems like it knows that there is no soundcard, regardless of its connection to pulseaudio.

**Comment by perexg** [comment]
> Forgive me if I'm not understanding what youre saying about the dummy sink. From my perspective it seems like it knows that there is no soundcard, regardless of its connection to pulseaudio.

Unfortunately, if pulseaudio comes to play, it's responsibility of the pulseaudio server to handle this. The aplay utility sends the PCM stream to the pulseaudio server using the pulse plugin (and the pulseaudio library) and the pulseaudio server accepts the connection / PCM stream. So aplay works from this perspective and there is no way to check, if the PCM stream ends in the dummy sink, because it's the internal setup of the pulseaudio server. The pulseaudio server may also use different permissions than the user, so the pulseaudio may have permissions for the audio devices even if the user is not in the audio group.

The `aplay -l` lists only the ALSA audio devices. The `aplay -L` lists the abstracted audio devices.

**Comment by perexg** [comment]
Also, don't forget, that pulseaudio may use the audio sinks which are defined purely in the user space like bluetooth. There is no ALSA bluetooth audio driver in the kernel.

**Comment by auwsom** [comment]
@perexg I see what youre saying. Ill have to check what `-L` reports in my case. And I do now see there is a `-v` flag for verbose that might reveal the problem. However, would agree that if there are no device names using `-L` (likely when pulseaudio isnt even running) and no soundcards found with `-l`, that aplay should report there are no sinks when trying to play? Or maybe more technically, if there are no audio sink servers listening? Is there any feedback to alsa when a server connects to it, or does alsa just broadcast without any particular endpoint? 

It just seems like there being "no soundcard found" is at least worthy of a warning message.

**Comment by perexg** [comment]
If the server is not running, you should see the connection error from the pulse plugin. Just stop PA like:

```
systemctl --user stop pulseaudio.socket
systemctl --user stop pulseaudio.service
```

**Comment by auwsom** [comment]
I was actually running it in the current Ubuntu docker container, which still uses SysV.

It sounds like you are looking at this from the top down, and I am from the bottom up.. kernel>alsa. I'm saying that as asla is closer to the kernel and physical devices, that if there are no devices, there should be an warning, even if on the upper layers there are virtual devices or other devices that go around alsa for some reason. It seems like alsa is primary, and so the lack of devices should be reported there, as logically that is where I started troubleshooting from.. the ground up (ie, the upper layers matters less). Hope that makes sense.

Here's a good image of how I'm looking at the audio system: https://askubuntu.com/a/581130/795299

**Comment by perexg** [comment]
> Here's a good image of how I'm looking at the audio system: https://askubuntu.com/a/581130/795299

If aplay is redirected to pulseaudio in the alsa-lib's configuration, you should take it as a normal application. No hardware binding. So it's on the top of the graph, not in the bottom. If you force to use the hardware devices (`aplay -l`, `aplay -D hw;0`) then it's in the bottom of the graph - connected to the ALSA drivers in kernel directly.

**Comment by auwsom** [comment]
Okay, so maybe the solution is that if alsa is set to be redirected in the configuration, there could be a message alerting the user that it is set to pass audio to another service so there might not be any sound and check if there are no soundcards found. If not, and there were no soundcards found, it could warn there definitely would be no sound when trying to play a file.

Either way, I hear you saying it is pulseaudio's responsibility to warn for no devices, so the same logic could used to say it is alsa's responsibility to warn if set to redirect audio so that it could not check for devices. Again alsa seems primary here as it can be used directly, whereas pusleaudio cannot.
