### ISSUE TITLE
pre-processor only works with relative path based on input file with the complete path

### ISSUE THREAD

**Issue by ranj063** [alsa-project/alsa-utils#123]
For ex:

`alsatplg -P sof-hda-generic.conf -o test.conf` fails with:

Unable to open included conf file sof-hda-generic.conf/include/components/eqiir/highpass_40hz_0db_48khz.conf
Unable to process include file 
Failed to process includes
Failed to process conditional includes in input config

whereas:

`alsatplg -P ~/work/sof/sof/tools/topology/topology2/sof-hda-generic.conf -o test.conf` works OK.

Would it be possible to make the first command work with the use of the ALSA_CONFIG_DIR environment variable?

**Comment by perexg** [comment]
The command `alsatplg -P ./sof-hda-generic.conf -o test.conf ` should work, too.

Fixed in https://github.com/alsa-project/alsa-utils/commit/7692cfa0c5699adcf489e281114910c078e43476 .

**Comment by ranj063** [comment]
@perexg but I have another problem with using ./sof-hda-generic.conf. Our build script pulls the ABI info from the SOF firmware source directory and adds it to the topology conf file before building it. And we do this outside the source directory in the build directory. So ./sof-hda-generic.conf won't work because the current directory in this case is the build directory.

**Comment by perexg** [comment]
There are two possibilities:

1) add new topology command line argument to override the default include path (which is based on the source file)
2) modify your build directory (add symlinks to missing source tree)

**Comment by ranj063** [comment]
Thanks @perexg. Option 1 sounds more appealing to me. The problem with option2 is that we do have symlinks to the source directory, but because we generate a new input conf file by adding the ABI information in it and the generated conf file goes into the build directory, I'd still be stuck with the original problem. I will submit a PR to add Option 1
