### ISSUE TITLE
Missing profile 7.1

### ISSUE THREAD

**Issue by raven2cz** [alsa-project/alsa-utils#128]
Hello,
I have several years profile 7.1 which is missing now around 1.5-2months. I already write these issues 
* https://bbs.archlinux.org/viewtopic.php?id=272280
* https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1309

It seems that the problem can be in alsa-utils.
```
control.45 {
                iface PCM
                name 'Playback Channel Map'
                value.0 0
                value.1 0
                value.2 0
                value.3 0
                value.4 0
                value.5 0
                comment {
                        access read
                        type INTEGER
                        count 6
                        range '0 - 36'
                }
        }
```
I already try to change kernels, not help. See inside the issues whole test env. 

Can you help me?

**Comment by perexg** [comment]
Answered in https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1309 .
