### ISSUE TITLE
QA issue with media-sound/alsa-utils-1.1.8 Gentoo package

### ISSUE THREAD

**Issue by fturco** [alsa-project/alsa-utils#13]
Portage (the Gentoo package manager) reports the following QA issue with `media-sound/alsa-utils-1.1.8`:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * ../alsamixer/volume_mapping.c:116:15: warning: incompatible implicit declaration of built-in function ‘exp10’
 * ../alsamixer/volume_mapping.c:151:14: warning: incompatible implicit declaration of built-in function ‘exp10’

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://alsa-project.org/
```

I'm using the `sys-devel/gcc-8.3.0-r1` compiler.

[info.txt](https://github.com/alsa-project/alsa-utils/files/3077834/info.txt)
[build.log](https://github.com/alsa-project/alsa-utils/files/3077835/build.log)

**Comment by smaeul** [comment]
This was fixed in 116488e5f2f1b897084bd151381ee254e1cc177d -- you can throw that in `/etc/portage/patches` or file a bug with Gentoo to get it added to the package.
