### ISSUE TITLE
compile error: undefined reference to `snd_ctl_elem_id_compare_set'

### ISSUE THREAD

**Issue by steeley** [alsa-project/alsa-utils#130]
Building on raspberry pi  buster (Linux 5.10.76-v7l. 32 bit) using theses commands:

`cd alsa-utils/
git checkout v1.2.6
autoreconf -i
./configure --prefix=/usr/local
make -j4`

I get this error:

`gcc -D_GNU_SOURCE -D__USE_GNU -DSYS_ASOUNDRC=\"/var/lib/alsa/asound.state\" -DSYS_LOCKFILE=\"/var/lock/asound.state.lock\" -DSYS_PIDFILE=\"/var/run/alsactl.pid\" -g -O2   -o alsactl alsactl-alsactl.o alsactl-state.o alsactl-lock.o alsactl-utils.o alsactl-init_parse.o alsactl-init_ucm.o alsactl-daemon.o alsactl-monitor.o alsactl-clean.o  -lasound -lm -ldl -lpthread
/usr/bin/ld: alsactl-clean.o: in function `clean_one_control':
/home/pi/alsa-utils/alsactl/clean.c:55: undefined reference to `snd_ctl_elem_id_compare_set'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:528: alsactl] Error 1
make[2]: Leaving directory '/home/pi/alsa-utils/alsactl'
make[1]: *** [Makefile:827: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/alsa-utils/alsactl'
make: *** [Makefile:429: all-recursive] Error 1`

**Comment by perexg** [comment]
This function is in alsa-lib 1.2.5+. You're linking against the old libraries.
