### ISSUE TITLE
"alsatplg -v 1 -o -"  silently corrupts output

### ISSUE THREAD

**Issue by marc-hb** [alsa-project/alsa-utils#131]
`alsatplg -v 1` works.
`alsatplg -o -` works too.

Using both produces silently a binary .tplg file prefixed with debug logs:

```
B0x003d3b/015675 - pcm 'DMIC': write 912 bytes
B0x0040cb/016587 - pcm 'HDMI1': write 912 bytes
B0x00445b/017499 - pcm 'HDMI2': write 912 bytes
B0x0047eb/018411 - pcm 'HDMI3': write 912 bytes
B0x004b7b/019323 - pcm 'DMIC16kHz': write 912 bytes
B0x004f0b/020235 - block size for type be (11:10) is 0x2ad4/10964
B0x004f0b/020235 - header index 0CoSA^E^@^@^@^@^@^@^@^H^@^@^@$^@^@
^@^@^@^@^@s^@^@^@^@^@^@^@^A^@^@^@p^@^@^@ ^@^@^@.^@^@^@ ^@^@^@^F^@^
@^@^F^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^...
```

I would have expected alsatplg -v to use stderr, this would have avoided this problem. Probably too late by now.

I suggest simply failing with an error message when both options are used at the same time. Any other solution that does not silently produces corrupted output would be a huge improvement.

Context: thesofproject/sof/pull/5132

**Comment by perexg** [comment]
Thanks for the report. The utility should abort when those parameters are mixed now.
