### ISSUE TITLE
alsamixer: `color` settings are not respected anymore

### ISSUE THREAD

**Issue by int-e** [alsa-project/alsa-utils#137]
`alsamixer` supports customizing colors for the various controls using the `color` directive in the configuration file. Commit

   https://github.com/alsa-project/alsa-utils/commit/5d4442b2cfe967c44b5cd74fccb62d1fb4095b19

broke this feature, because it initializes curses colors *after* reading the configuration file, which overrides any colors that the configuration file may have set.

**Comment by tiwai** [comment]
Now fixed, thanks for the report.
