### ISSUE TITLE
Mouse stopped working in xterm and rxvt-unicode

### ISSUE THREAD

**Issue by m-ou-se** [alsa-project/alsa-utils#139]
Since 1.2.6, I can't control alsamixer with my mouse's scroll wheel anymore in xterm and rxvt-unicode. I'm assuming it's related to this commit: https://github.com/alsa-project/alsa-utils/commit/31820c5f239fca2de12c8d1a7327ccf995188f33

**Comment by tiwai** [comment]
It seems that has_mouse() doesn't work as expected, unfortunately.
I reverted now.
