### ISSUE TITLE
`alsatplg` compile error `undefined source widget/stream` and `undefined sink widget/stream`

### ISSUE THREAD

**Issue by LazyGeniusMan** [alsa-project/alsa-utils#142]
Hi, I'm trying to do enable HDA+DMIC in my Kabylake R laptop using a guide[^1]. It's said to compile hda-dsp in  [alsa-topology-conf](https://github.com/alsa-project/alsa-topology-conf), but I got this error:
```
[lazygeniusman@archlinux hda-dsp]$ alsatplg -c skl_hda_dsp_generic-tplg.conf -o skl_hda_dsp_generic-tplg.bin
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'hda-dsp-analog-playback'
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'hda-dsp-digital-playback'
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'hda-dsp-alt-analog-playback'
ALSA lib dapm.c:225:(tplg_build_routes) undefined sink widget/stream 'hda-dsp-audio-analog-capture'
ALSA lib dapm.c:225:(tplg_build_routes) undefined sink widget/stream 'hda-dsp-audio-digital-capture'
ALSA lib dapm.c:225:(tplg_build_routes) undefined sink widget/stream 'hda-dsp-audio-alt-analog-capture'
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'HDMI1 Playback'
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'HDMI2 Playback'
ALSA lib dapm.c:247:(tplg_build_routes) undefined source widget/stream 'HDMI3 Playback'
ALSA lib dapm.c:225:(tplg_build_routes) undefined sink widget/stream 'DMIC-Capture'
```
it's also have same error when I run `make firmware` in the repo root dir

Could someone help me solve it?

EDIT1: error -13 solved but the undefined source and sink error still there

[^1]: https://gist.github.com/crojewsk/4e6382bfb0dbfaaf60513174211f29cb#topology

**Comment by amadeuszslawinski-intel** [comment]
Hi,
$ errno 13
EACCES 13 Permission denied
Sounds like you don't have right to write in directory? Try moving the file somewhere else or use sudo.

**Comment by LazyGeniusMan** [comment]
Oh I forgot to update it, that error no longer there after I delete the old bin (this is my second run because I clear the output

**Comment by amadeuszslawinski-intel** [comment]
Messages "undefined source widget/stream" are expected, they are for information purposes only. Remaining widgets are created by kernel.

**Comment by LazyGeniusMan** [comment]
Ah ok I thought it's failed, the guide also working as intended. Thanks.
