### ISSUE TITLE
how can i swich between sound card without reboot in archlinux

### ISSUE THREAD

**Issue by EN-KS** [alsa-project/alsa-utils#144]
I use riverwm and kitty. Currently there is no sound output when i try to plugin a usb 2.4G wireless headset in and then use alsamixer F6 to select the usb sound card unless I leave the usb adapter on the machine and reboot. the usb sound card was detected tho, Is this what it suppose to be? or any procedure that I missed?

**Comment by perexg** [comment]
I am afraid, this issue tracker is specific for the ALSA subsystem. Try to ask on the distribution specific forum.
