### ISSUE TITLE
Weaknesses in alsa_info on new Ubuntu systems

### ISSUE THREAD

**Issue by mhampl** [alsa-project/alsa-utils#146]
There are some weaknesses on current Ubuntu systems (e.g. release 22.04) where the alsa_info scripts does not deliver the desired information:

The command "tree" is no more provided by default (but can be installed in addition)
This results in the error message
"./alsa-info.sh: line 661: tree: command not found"
and causes missing output in "Sysfs card info"

The command "dmesg" requires administrative authorizations (e.g. "sudo dmesg | grep ...")
This results in the error message
"dmesg: read kernel buffer failed: Operation not permitted"
and causes missing output in "ALSA/HDA dmesg"

**Comment by geraldog** [comment]
I speak for myself only, not for the ALSA project. That being said I think this should be dealt with downstream. ALSA project can't guarantee all systems will have sudo installed, for example. And, minor rant, having sudo installed on a system is way bigger an attack surface than being able to read the kernel's message ring buffer.

**Comment by perexg** [comment]
The alsa-info script is part of the alsa-utils package. Ask Ubuntu support to add the necessary package dependencies to their alsa-utils package.

The alsa-info script is supposed to be run as `root` to gather all necessary information. So users should use sudo on the whole script.
