### ISSUE TITLE
"topology: nhlt plugin: second attempt to fix the .so linking" cause build static library failed

### ISSUE THREAD

**Issue by youling257** [alsa-project/alsa-utils#152]
./configure --prefix=/system/usr --with-alsa-inc-prefix=/system/usr/include --with-alsa-prefix=/system/usr/lib --enable-static=yes --enable-shared=no
make LDFLAGS="--static" -j8

Revert "topology: nhlt plugin: second attempt to fix the .so linking" can build static library.

**Comment by perexg** [comment]
Note that it does not make sense to build static topology modules. They are not usable.
