### ISSUE TITLE
1.1.8: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [alsa-project/alsa-utils#16]
<pre>+ /usr/bin/make -O -j4 check
Making check in include
Making check in alsactl
Making check in init
make[2]: Nothing to be done for &apos;check&apos;.
make[2]: Nothing to be done for &apos;check-am&apos;.
Making check in utils
make[1]: Nothing to be done for &apos;check&apos;.
Making check in m4
make[1]: Nothing to be done for &apos;check&apos;.
Making check in po
make[1]: Nothing to be done for &apos;check&apos;.
Making check in alsa-info
make[1]: Nothing to be done for &apos;check&apos;.
Making check in alsamixer
make[1]: Nothing to be done for &apos;check&apos;.
Making check in amixer
make[1]: Nothing to be done for &apos;check&apos;.
Making check in amidi
make[1]: Nothing to be done for &apos;check&apos;.
Making check in aplay
make[1]: Nothing to be done for &apos;check&apos;.
Making check in iecset
make[1]: Nothing to be done for &apos;check&apos;.
Making check in speaker-test
Making check in samples
make[2]: Nothing to be done for &apos;check&apos;.
make[2]: Nothing to be done for &apos;check-am&apos;.
Making check in axfer
Making check in test
/usr/bin/make  container-test mapper-test
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o container-au.o `test -f &apos;../container-au.c&apos; || echo &apos;./&apos;`../container-au.c
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o container-riff-wave.o `test -f &apos;../container-riff-wave.c&apos; || echo &apos;./&apos;`../container-riff-wave.c
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o generator.o generator.c
generator.c:9:10: fatal error: generator.h: No such file or directory
    9 | #include &quot;generator.h&quot;
      |          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:640: generator.o] Error 1
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
make[3]: *** Waiting for unfinished jobs....
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o container.o `test -f &apos;../container.c&apos; || echo &apos;./&apos;`../container.c
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o container-voc.o `test -f &apos;../container-voc.c&apos; || echo &apos;./&apos;`../container-voc.c
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o container-raw.o `test -f &apos;../container-raw.c&apos; || echo &apos;./&apos;`../container-raw.c
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test&apos;
make[2]: *** [Makefile:1017: check-am] Error 2
make[1]: *** [Makefile:650: check-recursive] Error 1
make: *** [Makefile:428: check-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.VI5lrR (%check)
</pre>

**Comment by takaswie** [comment]
```
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/alsa-utils-1.1.8/axfer/test'
gcc -DHAVE_CONFIG_H -I. -I../../include     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -c -o generator.o generator.c
generator.c:9:10: fatal error: generator.h: No such file or directory
    9 | #include "generator.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
```

This was fixed by 6fdaa0c52412205017a9a71872169c75f3d3a542.

Thanks

**Comment by kloczek** [comment]
Just checked and still after add that patch test suite fails in the same point.
BTW: it is as well few warnings about implicit declaration
All you will find in attached package build log.
[alsa-utils.log](https://github.com/alsa-project/alsa-utils/files/3150991/alsa-utils.log)

**Comment by takaswie** [comment]
> Just checked and still after add that patch test suite fails in the same point.
> BTW: it is as well few warnings about implicit declaration

Yes.

As long as utilizing official v1.1.8 release, some files are still missing even if applying the patch.

**Comment by kloczek** [comment]
So .. maybe it would be good to make new release? :)

**Comment by perexg** [comment]
Yes, this or next week.

**Comment by perexg** [comment]
1.1.9 is out.
