### ISSUE TITLE
AM_PATH_ALSA

### ISSUE THREAD

**Issue by magic-tab-01** [alsa-project/alsa-utils#190]
hi 
when i compile it with"autoreconf -i", some error output in the screen, i can't find any solution, could you kindly help?
the error as follows:

configure.ac:22: warning: macro 'AM_PATH_ALSA' not found in library
configure.ac:22: error: possibly undefined macro: AM_PATH_ALSA
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by perexg** [comment]
It seems that m4 macros from alsa-lib are not installed in your system.

**Comment by magic-tab-01** [comment]
> It seems that m4 macros from alsa-lib are not installed in your system.

really appreciate for your quickly help, thank you

**Comment by magic-tab-01** [comment]
solved, thank you
