### ISSUE TITLE
High CPU usage in mpd

### ISSUE THREAD

**Issue by buttjake** [alsa-project/alsa-utils#2]
I've ran into a strange bug in mpd where I get really high cpu usage. All the details are in the following two short threads.
https://github.com/MusicPlayerDaemon/MPD/issues/391#issuecomment-435698235
https://bbs.archlinux.org/viewtopic.php?id=241722 ( buttcake is me )
I can also solve the bug by adding
```
audio_output {
 type	"alsa"
 device	"hw:0,0"
}
```
to the mpd.conf

**Comment by perexg** [comment]
I replied to the MPD bug https://github.com/MusicPlayerDaemon/MPD/issues/391#issuecomment-436948394 .

**Comment by buttjake** [comment]
Thank you.
