### ISSUE TITLE
Looking for alsaunmute script

### ISSUE THREAD

**Issue by DenverEllis** [alsa-project/alsa-utils#211]
I have a friend that is having trouble with their legion 7 laptop. Perusing a very long kernel thread I saw mention of an alsaunmute script and I am having a hard time tracking it down. I believ perex authored it and I saw it mentioned that it was a part of alsa-utils, but alas I have had no luck in finding this script.

**Comment by perexg** [comment]
The alsaunmute script is specific for the Fedora distribution. It's invokes only `alsactl init` nowadays.
