### ISSUE TITLE
"alsactl restore" does not load the driver state

### ISSUE THREAD

**Issue by YuGiOhJCJ** [alsa-project/alsa-utils#229]
Hello,

When I type "alsactl restore", it does not load the driver state.

Steps to reproduce:
1. Open a first terminal dedicated to alsa-mixer
2. Open a second terminal where you will type the following commands
3. In the first terminal, press F4, set the audio volume for capture to 40
4. In the second terminal, type "sudo alsactl store" in order to save the driver state to /var/lib/alsa/asound.state
5. In the first terminal, set the audio volume for capture to 35
6. In the second terminal, type "sudo alsactl restore" in order to load the driver state from /var/lib/alsa/asound.state

Expected results: I should see in the first terminal that the audio volume for capture is restored to 40.

Current results: I see in the first terminal that the audio volume for capture is not restored to 40. It is still set to 35!

How to fix that please?

Thank you.
Best regards.

About my system:

Packages:
- alsa-lib-1.2.9
- alsa-plugins-1.2.7.1
- alsa-utils-1.2.9

Operating system: Slackware 14.2 (64-bit)

Architecture: x86_64

Kernel: Linux 5.18.10

![image](https://github.com/alsa-project/alsa-utils/assets/2247896/d4cc947f-b8db-493f-bf03-f18af9c821b3)

**Comment by perexg** [comment]
PulseAudio compatible interface does not create an ALSA sound card. Application using only specific interfaces like mixer are working, but alsactl works only on the sound card level. Use PulseAudio tools to handle volume settings - store/restore (it should work by default - command line command `pactl set-sink-volume`).
