### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by symdeb** [alsa-project/alsa-utils#230]
Follow INSTALL

$ls -l
total 148
-rw-rw-r-- 1 user user   440 Aug 16 17:40 acinclude.m4
drwxrwxr-x 3 user user  4096 Aug 16 17:40 alsaconf
drwxrwxr-x 3 user user  4096 Aug 16 17:40 alsactl
drwxrwxr-x 2 user user  4096 Aug 16 17:40 alsa-info
drwxrwxr-x 2 user user  4096 Aug 16 17:40 alsaloop
drwxrwxr-x 2 user user  4096 Aug 16 17:40 alsamixer
drwxrwxr-x 2 user user  4096 Aug 16 17:40 alsaucm
drwxrwxr-x 2 user user  4096 Aug 16 17:40 amidi
drwxrwxr-x 2 user user  4096 Aug 16 17:40 amixer
drwxrwxr-x 2 user user  4096 Aug 16 17:40 aplay
drwxrwxr-x 3 user user  4096 Aug 16 17:40 axfer
drwxrwxr-x 3 user user  4096 Aug 16 17:40 bat
-rw-rw-r-- 1 user user  1055 Aug 16 17:40 ChangeLog
-rw-rw-r-- 1 user user 17587 Aug 16 17:40 configure.ac
-rw-rw-r-- 1 user user 18002 Aug 16 17:40 COPYING
-rwxrwxr-x 1 user user   780 Aug 16 17:40 gitcompile
drwxrwxr-x 2 user user  4096 Aug 16 17:40 iecset
drwxrwxr-x 2 user user  4096 Aug 16 17:40 include
-rw-rw-r-- 1 user user  1595 Aug 16 17:40 INSTALL
drwxrwxr-x 2 user user  4096 Aug 16 17:40 m4
-rw-rw-r-- 1 user user  1063 Aug 16 17:40 Makefile.am
drwxrwxr-x 2 user user  4096 Aug 16 17:40 nhlt
drwxrwxr-x 2 user user  4096 Aug 16 17:40 po
-rw-rw-r-- 1 user user  1392 Aug 16 17:40 README.md
drwxrwxr-x 6 user user  4096 Aug 16 17:40 seq
drwxrwxr-x 3 user user  4096 Aug 16 17:40 speaker-test
-rw-rw-r-- 1 user user   187 Aug 16 17:40 TODO
drwxrwxr-x 3 user user  4096 Aug 16 17:40 topology
drwxrwxr-x 2 user user  4096 Aug 16 17:40 utils

$aclocal
$gettextize
Copying file ABOUT-NLS
Copying file config.rpath
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
Creating po/ChangeLog
Copying file m4/gettext.m4
Copying file m4/host-cpu-c-abi.m4
Copying file m4/iconv.m4
Copying file m4/intlmacosx.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/progtest.m4
Updating EXTRA_DIST in m4/Makefile.am (backup is in m4/Makefile.am~)
Updating configure.ac (backup is in configure.ac~)
Adding an entry to ChangeLog (backup is in ChangeLog~)

Please run 'aclocal -I m4' to regenerate the aclocal.m4 file.
You need aclocal from GNU automake 1.9 (or newer) to do this.
Then run 'autoconf' to regenerate the configure file.

You will also need config.guess and config.sub, which you can get from the CVS
of the 'config' project at https://savannah.gnu.org/. The commands to fetch them
are
$ wget 'https://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess'
$ wget 'https://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub'

You might also want to copy the convenience header file gettext.h
from the /usr/share/gettext directory into your package.
It is a wrapper around <libintl.h> that implements the configure --disable-nls
option.

Press Return to acknowledge the previous three paragraphs.

$autoheader
configure.ac:480: error: `po/Makefile.in' is already registered with AC_CONFIG_FILES.
./lib/autoconf/status.m4:289: AC_CONFIG_FILES is expanded from...
configure.ac:480: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
autoheader: error: '/usr/bin/autom4te' failed with exit status: 1

$automake --foreign --copy --add-missing
configure.ac:480: error: `po/Makefile.in' is already registered with AC_CONFIG_FILES.
./lib/autoconf/status.m4:289: AC_CONFIG_FILES is expanded from...
configure.ac:480: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1

$aclocal -I m4
configure.ac:480: error: `po/Makefile.in' is already registered with AC_CONFIG_FILES.
./lib/autoconf/status.m4:289: AC_CONFIG_FILES is expanded from...
configure.ac:480: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1

./configure
bash: ./configure: No such file or directory

aclocal --version
aclocal (GNU automake) 1.16.5

**Comment by perexg** [comment]
Use the `gitcompile` script - https://github.com/alsa-project/alsa-utils/blob/master/gitcompile . Or remove the duplicate `po/Makefile.in` manually from configure.ac .

**Comment by symdeb** [comment]
Could not recover from the condition somehow. Recloned the repo and just ran ./gitcompile worked.
