### ISSUE TITLE
alsa-utils 1.2.10 fails to build with old gcc

### ISSUE THREAD

**Issue by tiwai** [alsa-project/alsa-utils#233]
The recent change for fixes builds on the latest gcc broke the builds on the older gcc version instead.
The truncated parameters can't be handled well by the older gcc.

I guess we should rather add the option to ignore the unused parameters instead of truncating unused parameters. Not all compilers support those new syntax.

**Comment by perexg** [comment]
Ok, thanks. It seems that GCC 11+ only supports this feature:

https://en.cppreference.com/w/c/compiler_support
[N2480 Allowing unnamed parameters in a function definition (pdf)](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2480.pdf)

I think that we should probably go back to ATTRIBUTE_UNUSED - `__attribute__ ((__unused__))` marks.

**Comment by perexg** [comment]
Ok, above commits should fix this issue. Tested with gcc 4.8.5.

**Comment by tiwai** [comment]
FWIW, I checked gcc7 and gcc12.

**Comment by duhow** [comment]
Just facing this issue in `1.2.10` with `gcc-7.4.0` for linaro ARM, was working in previous `1.2.4`, I am currently patching about 12 files....
