### ISSUE TITLE
Left audio channel very loud when external sound card was unplugged, volume not reflected properly in alsamixer

### ISSUE THREAD

**Issue by WildRikku** [alsa-project/alsa-utils#235]
I'm reporting this here because alsamixer is at least part of the issue. I'd be thankful for help finding the whole issue and I can report elsewhere if necessary.

After plugging in my external sound card, the left channel is WAY louder than the right channel but `alsamixer` does not reflect this. I then correct it by setting the left channel to zero in `alsamixer` and back to what it should be. Note that it showed the value it should have before already, it just wasn't true! The volume is then correct until I unplug my sound card the next time and plug it in again. The issue also happens when I turn off the power supply of the USB dock the external sound card is plugged into. My device is a Steam Deck so I cannot use the external sound card without a dock.

#### Steps for reproducing this issue:

1. Unplug external sound card from the dock or send Steam Deck to stand-by and unplug the power supply
2. Plug sound card in or plug power supply in and turn on Steam Deck
3. left channel is now very loud but `alsamixer` shows equal value for left and right channel

Maybe related: When using `alsactl restore` I get

```
alsactl: set_control:1475: Cannot write control '2:0:0:Left Speaker Port Blocked Status:0' : Operation not permitted
alsactl: set_control:1475: Cannot write control '2:0:0:Left Speaker Open / Short Status:0' : Operation not permitted
alsactl: set_control:1475: Cannot write control '2:0:0:Right Speaker Port Blocked Status:0' : Operation not permitted
alsactl: set_control:1475: Cannot write control '2:0:0:Right Speaker Open / Short Status:0' : Operation not permitted
```

alsa-info output: https://alsa-project.org/db/?f=69b87861217a0e554cb4786c64d4a0c461177fdd

**Comment by perexg** [comment]
You report this for the external USB card Fast Track C400 or for the internal hardware?

**Comment by Konzertheld** [comment]
> You report this for the external USB card Fast Track C400 or for the internal hardware?

I am reporting this with all audio devices deactivated except the Fast Track C400. The Steam Deck also has an HDMI audio output and another audio output which I both turned off using the "volume control" GUI tool.

**Comment by WildRikku** [comment]
Update: This also happens in "Steam mode" (which is kinda like Steam Big Picture mode). Might help if someone who knows SteamOS well comes across this... but it corroborates my idea that the issue is at least not only alsamixer displaying the wrong value. So if you have any idea where I could post the issue I will gladly take the advice.

**Comment by perexg** [comment]
This looks like a kernel driver issue (or a firmware issue for the USB sound card or another USB related kernel issue). You may discuss this at linux-sound@vger.kernel.org .
