### ISSUE TITLE
Using amixer to reduce right speaker volume to zero(and leave left unchanged)

### ISSUE THREAD

**Issue by sierret** [alsa-project/alsa-utils#269]
I'm trying to right a script to reduce my right speaker volume to 0. I know the code:

`amixer -D pulse sset Master -,0`

sets the LEFT speaker to zero and leaves the right unchanged. However, for the life of me I can't manage to modify this code to do the opposite. And there don't seem to be adequate resources directing how to do so floating around the interwebs.

**Comment by perexg** [comment]
I suggest to look into manual:

```
amixer -D pulse -- sset Master -,0
amixer -D pulse -- sset Master 0,-
```

Or:

```
amixer -D pulse sset Master frontleft 0
amixer -D pulse sset Master frontright 0
```
