### ISSUE TITLE
ThinkPad P14s Gen 5 AMD micmute LED is not working sometimes.

### ISSUE THREAD

**Issue by pma1** [alsa-project/alsa-utils#278]
The mic and sound output works fine.
The mute LED works fine.
But when press Fn+F4, the mic-mute led is not working sometimes after bootup.
The failrate is like 1/10.

Tested with latest alsa-ucm from git, it's reproduced.
/sys/class/sound/ctl-led/mic/card1# cat list
7
# amixer -c 1 controls
numid=12,iface=CARD,name='Headphone Jack'
numid=11,iface=CARD,name='Mic Jack'
numid=13,iface=CARD,name='Speaker Phantom Jack'
numid=10,iface=MIXER,name='Master Playback Switch'
numid=9,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Headphone Playback Switch'
numid=1,iface=MIXER,name='Headphone Playback Volume'
numid=16,iface=MIXER,name='PCM Playback Volume'
numid=17,iface=MIXER,name='Mic ACP LED Capture Switch'
numid=8,iface=MIXER,name='Mic Boost Volume'
numid=7,iface=MIXER,name='Capture Switch'
numid=6,iface=MIXER,name='Capture Volume'
numid=5,iface=MIXER,name='Auto-Mute Mode'
numid=4,iface=MIXER,name='Speaker Playback Switch'
numid=3,iface=MIXER,name='Speaker Playback Volume'
numid=15,iface=PCM,name='Capture Channel Map'
numid=14,iface=PCM,name='Playback Channel Map'

# echo 'Capture Switch' > detach
# echo 'Mic ACP LED Capture Switch' > attach
/sys/class/sound/ctl-led/mic/card1# cat list
17

Then the micmute LED will work.
[alsa-info-amd-micmutled.txt](https://github.com/user-attachments/files/16279936/alsa-info-amd-micmutled.txt)

**Comment by cladmi** [comment]
Thanks!

Arch linux release 1.2.13 and I could test this. Now working as expected.

Did reboot 3 times, was working each time with the micmute led state following the mic mute status.
For me it was never turning off before (so not concerned with the 1/10 rate of OP). Assuming that the 3 reboots were enough on my side for testing.
