### ISSUE TITLE
`amixer sset Master` doesnt increase and decrease both sides equally

### ISSUE THREAD

**Issue by lquenti** [alsa-project/alsa-utils#279]
I look through the issues, man pages and internet and hope I didn't miss anything. Please tell me if its a user error.

Whenever I use `amixer sset Master` to increase volume, it will not increase them evenly.

Here is a before

![before](https://github.com/user-attachments/assets/4ccfa220-608c-4407-9f6e-fc1d27f1a91b)

and after

![after](https://github.com/user-attachments/assets/250ab254-d46a-44e4-a201-58f9224b6293)

Interestingly amixer seem to think that it is still evenly balanced, although alsamixer shows that it is unbalanced afterwards.

---

Interestingly, when decreasing, the unevenness flips to the other side.

[Other people also seem to struggle with it](https://stackoverflow.com/questions/69826139/using-amixer-to-set-audio-makes-left-and-right-unbalanced) 

Thank you so much. If it is something somewhat simple to fix, I can also write a fix myself, but for now I am unsure what the problem is.

**Comment by perexg** [comment]
We cannot do much for it here. It's a pipewire ALSA plugin issue - so you should report this problem to pipewire developers. Basically, if you restart alsamixer, the levels are fine as amixer reports. It looks like that the "mixer element change event" handling does not work properly in the pipewire plugin. The amixer utility sets left/right channels separately and the change event seems triggered only for the first one.
