### ISSUE TITLE
amixer: "5%-" or "5%+" doesn't work with cset

### ISSUE THREAD

**Issue by MarioMey** [alsa-project/alsa-utils#32]
I want to raise and low volume with keys. This works, this rise the volume 20%:

`amixer set Master 20%+`

And every time I run this command, it rise 20% more. But, when I want to use the card (because I need to do this):

`amixer -c 0 cset name='Master Playback Volume' 20%+`

It doesn't work. It seems that amixer takes only "20%" value and doesn't care about "+" or "-".

I have Debian Buster, Mate desktop.

```
mario@debian:~/$ apt-cache showpkg alsa-tools
Package: alsa-tools
Versions: 
1.1.7-1 (/var/lib/apt/lists/ftp.us.debian.org_debian_dists_buster_main_binary-amd64_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/ftp.us.debian.org_debian_dists_buster_main_binary-amd64_Packages
                  MD5: 4d64eace7e51fb1fc1a18ed780ee5e62
 Description Language: en
                 File: /var/lib/apt/lists/ftp.us.debian.org_debian_dists_buster_main_i18n_Translation-en
                  MD5: 4d64eace7e51fb1fc1a18ed780ee5e62


Reverse Depends: 
  ld10k1,alsa-tools
  multimedia-jack,alsa-tools
Dependencies: 
1.1.7-1 - libasound2 (2 1.0.16) libc6 (2 2.7) libgcc1 (2 1:3.0) libglib2.0-0 (2 2.12.0) libstdc++6 (2 5) as10k1 (0 (null)) as10k1 (0 (null)) 
Provides: 
1.1.7-1 - as10k1 (= ) 
Reverse Provides: 

```

**Comment by perexg** [comment]
You may try:

`amixer -c 0 set Master 20%+`

You're right that the cset does not support the incremental changes.

**Comment by MarioMey** [comment]
Ok, it does work. If this is a design decision, then I close this report.
