### ISSUE TITLE
Build failure without alsa-topology

### ISSUE THREAD

**Issue by ffontaine** [alsa-project/alsa-utils#33]
Commit c8fdd38c74de2e8b7b2b5a4576787d5e9b4ae807 breaks build of alsa-utils on buildroot because $(ALSA_TOPOLOGY_LIBS) is set to an empty value by https://github.com/alsa-project/alsa-lib/commits/master/utils/alsa.m4 if --enable-alsa-topology is not passed:
```
/home/br-user/autobuild/run/instance-0/output/host/bin/arm-linux-gnueabihf-gcc  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2     -o alsatplg topology.o  -lasound -lm -ldl -lpthread
topology.o: In function `main':
topology.c:(.text.startup+0x184): undefined reference to `snd_tplg_new'
topology.c:(.text.startup+0x194): undefined reference to `snd_tplg_verbose'
topology.c:(.text.startup+0x1a4): undefined reference to `snd_tplg_build_file'
topology.c:(.text.startup+0x1b4): undefined reference to `snd_tplg_free'
topology.c:(.text.startup+0x218): undefined reference to `snd_tplg_free'
```

More information can be found here: http://autobuild.buildroot.org/results/d0f/d0fb760669b02b813115af04adcf24530d35f4e1/build-end.log

**Comment by perexg** [comment]
Fixed in f77a269370af917585df59d8c21c89bca07b5b73 . Thanks.
