### ISSUE TITLE
amixer not setting Master volume at a given percentage value (check with 85% to 90%)

### ISSUE THREAD

**Issue by immortalaxay** [alsa-project/alsa-utils#35]
I am using Ubuntu 18.04 (alsa-utils/amixer version 1.1.3) and trying to set volume using amixer command but amixer not setting Master volume at the given percentage value.

$ amixer -M -c PCH sset Master **85**%
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 81 [**83**%] [-4.50dB] [on]

$ amixer -M -c PCH sset Master **86**%
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 82 [**85**%] [-3.75dB] [on]

$ amixer -M -c PCH sset Master **87**%
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 82 [**85**%] [-3.75dB] [on]

$ amixer -M -c PCH sset Master **88**%
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 82 [**85**%] [-3.75dB] [on]

$ amixer -M -c PCH sset Master **89**%
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 83 [**88**%] [-3.00dB] [on]

$ amixer -M -c PCH sset Master **90**%
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 83 [**88**%] [-3.00dB] [on]

**Comment by cladisch** [comment]
The hardware has fewer than 100 steps, so the percent values must be rounded.

**Comment by immortalaxay** [comment]
> The hardware has fewer than 100 steps, so the percent values must be rounded.

When 89% is set, it returns 88%. Let it is due to round off
When 88% is set, it returns 85%. It should return 88%, as 88% can be set.

**Comment by perexg** [comment]
Fixed in latest alsa-lib / alsa-utils.
