### ISSUE TITLE
Unable to use alsa utils with card who have id greather than 31

### ISSUE THREAD

**Issue by F4HTB** [alsa-project/alsa-utils#36]
Hello Dear Alsa dev members, 

I comme to you because i search to use multiple alsa loopback.
Unfortunatly by defaut all is blocked on a id maximum to 31 (32 sound cards).
I compile a kernel with the options `CONFIG_SND_MAX_CARDS = 256.`

I add this options in the /etc/modprobe.d/alsa-base.conf:

```
options snd-aloop \
index=10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32 \
id=lp0,lp1,lp2,lp3,lp4,lp5,lp6,lp7,lp8,lp9,lp10,lp11,lp12,lp13,lp14,lp15,lp16,lp17,lp18,lp19,lp20,lp21,lp22 \
enable=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 \
pcm_substreams=2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2 /

```
As you can see, i try to use ID greather than 31.

When i look to /proc/asound:
```
card10/  card17/  card24/  card31/  lp11/    lp18/    lp4/     oss/
card11/  card18/  card25/  card32/  lp12/    lp19/    lp5/     pcm
card12/  card19/  card26/  cards    lp13/    lp2/     lp6/     seq/
card13/  card20/  card27/  devices  lp14/    lp20/    lp7/     timers
card14/  card21/  card28/  lp0/     lp15/    lp21/    lp8/     version
card15/  card22/  card29/  lp1/     lp16/    lp22/    lp9/
card16/  card23/  card30/  lp10/    lp17/    lp3/     modules
```

I find my card with id 32.

I have try first to use speakertest and i get :
```
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
Erreur d'ouverture à la lecture: -22,Invalid argument
```

I have try to compile alsa-lib and alsa-utils with:

```
mkdir /usr/src/alsa
cd /usr/src/alsa

git clone git://git.alsa-project.org/alsa-lib.git alsa-lib
cd /usr/src/alsa/alsa-lib
./gitcompile --with-max-cards=256
make install

cd /usr/src/alsa

git clone git://git.alsa-project.org/alsa-utils.git alsa-utils
cd /usr/src/alsa/alsa-utils
./gitcompile --with-max-cards=256
make install

```

But i have alwais the same issue.

Can somme one help me please?

**Comment by perexg** [comment]
It seems that snd_card_get_index() returns this error, but SND_MAX_CARDS is used there, so it should return this error for >256 only.

Could you check strace, if the kernel driver returns this error?

**Comment by perexg** [comment]
Also, make sure that the compiled libasound is used. 'make install' might install library to another location than the distro is using.

**Comment by F4HTB** [comment]
Hello, 

Thanks for reply.

I have search libasound and get: 

`/var/lib/dpkg/info/libasound2:amd64.symbols
/var/lib/dpkg/info/libasound2:amd64.triggers
/var/lib/dpkg/info/libasound2:amd64.md5sums
/var/lib/dpkg/info/libasound2-data.list
/var/lib/dpkg/info/libasound2:amd64.list
/var/lib/dpkg/info/libasound2-plugins:amd64.md5sums
/var/lib/dpkg/info/libasound2-plugins:amd64.list
/var/lib/dpkg/info/libasound2:amd64.shlibs
/var/lib/dpkg/info/libasound2-data.md5sums
/usr/src/alsa/alsa-lib/src/libasound.la
/usr/src/alsa/alsa-lib/src/.libs/libasound.lai
/usr/src/alsa/alsa-lib/src/.libs/libasound.la
/usr/src/alsa/alsa-lib/src/.libs/libasound.so.2
/usr/src/alsa/alsa-lib/src/.libs/libasound.so
/usr/src/alsa/alsa-lib/src/.libs/libasound.so.2.0.0
/usr/src/alsa/alsa-utils/axfer/xfer-libasound-irq-rw.o
/usr/src/alsa/alsa-utils/axfer/.deps/xfer-libasound-irq-rw.Po
/usr/src/alsa/alsa-utils/axfer/.deps/xfer-libasound-timer-mmap.Po
/usr/src/alsa/alsa-utils/axfer/.deps/xfer-libasound-irq-mmap.Po
/usr/src/alsa/alsa-utils/axfer/.deps/xfer-libasound.Po
/usr/src/alsa/alsa-utils/axfer/xfer-libasound-irq-rw.c
/usr/src/alsa/alsa-utils/axfer/xfer-libasound.c
/usr/src/alsa/alsa-utils/axfer/xfer-libasound-timer-mmap.c
/usr/src/alsa/alsa-utils/axfer/xfer-libasound-irq-mmap.o
/usr/src/alsa/alsa-utils/axfer/xfer-libasound-timer-mmap.o
/usr/src/alsa/alsa-utils/axfer/xfer-libasound.o
/usr/src/alsa/alsa-utils/axfer/xfer-libasound-irq-mmap.c
/usr/src/alsa/alsa-utils/axfer/xfer-libasound.h
/usr/share/doc/libasound2-data
/usr/share/doc/libasound2-data/changelog.Debian.gz
/usr/share/doc/libasound2-data/copyright
/usr/share/doc/libasound2-plugins
/usr/share/doc/libasound2-plugins/speexrate.txt
/usr/share/doc/libasound2-plugins/upmix.txt
/usr/share/doc/libasound2-plugins/README-arcam-av
/usr/share/doc/libasound2-plugins/README-pulse
/usr/share/doc/libasound2-plugins/changelog.Debian.gz
/usr/share/doc/libasound2-plugins/examples
/usr/share/doc/libasound2-plugins/examples/asound.conf_oss
/usr/share/doc/libasound2-plugins/examples/asound.conf_jack
/usr/share/doc/libasound2-plugins/examples/a52.conf_pulse
/usr/share/doc/libasound2-plugins/README-maemo.gz
/usr/share/doc/libasound2-plugins/speexdsp.txt
/usr/share/doc/libasound2-plugins/samplerate.txt
/usr/share/doc/libasound2-plugins/lavcrate.txt
/usr/share/doc/libasound2-plugins/vdownmix.txt
/usr/share/doc/libasound2-plugins/README-jack
/usr/share/doc/libasound2-plugins/copyright
/usr/share/doc/libasound2-plugins/a52.txt
/usr/share/doc/libasound2-plugins/README-pcm-oss
/usr/share/doc/libasound2
/usr/share/doc/libasound2/NEWS.Debian.gz
/usr/share/doc/libasound2/changelog.Debian.gz
/usr/share/doc/libasound2/examples
/usr/share/doc/libasound2/examples/asoundrc.txt.gz
/usr/share/doc/libasound2/copyright
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_arcam_av.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_speexrate_medium.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_vdownmix.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_speex.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_jack.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_samplerate.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_samplerate_best.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_samplerate_medium.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_samplerate_linear.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_oss.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_oss.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_usb_stream.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_speexrate.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_upmix.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_conf_pulse.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_speexrate_best.so
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_rate_samplerate_order.so
/usr/lib/x86_64-linux-gnu/libasound.so.2
/usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
/usr/lib/libasound.la
/usr/lib/libasound.so.2
/usr/lib/libasound.so
/usr/lib/libasound.so.2.0.0
`

I have remove /usr/lib/libasound* (by apt and manualy vérificating).
After make install lib compiled in 256 are in place.
Nothing new.

But, i dont no if it's good but i have remove /usr/lib/x86_64-linux-gnu/libasound* and after that it was good!

I have search so many days before find that!
