### ISSUE TITLE
Volume is not restored after boot

### ISSUE THREAD

**Issue by Oscar65** [alsa-project/alsa-utils#39]
I have archlinux updated system last sunday.

```
$ uname -a
Linux mypc 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux
```

I checked with alsa-restore.service and alsa-state.service. None of them work as expected.

My sound card is:
```
# lshw -C sound
  *-multimedia              
       description: Audio device
       product: 82801H (ICH8 Family) HD Audio Controller
       vendor: Intel Corporation
       physical id: 1b
       bus info: pci@0000:00:1b.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: driver=snd_hda_intel latency=0
       resources: irq:29 memory:ffaf8000-ffafbfff
```

Every time that my system boots the volume levels are different than last time a powered off.

**Comment by perexg** [comment]
Could you check, if /var/lib/alsa/asound.state file is updated when you change the mixer settings ? Is alsactl daemon running ?

**Comment by Oscar65** [comment]
When I change mixer settings with alsamixer the file /var/lib/alsa/asound.state don't change immediately. It takes about five minutes to change (checked the updated time with ls -l) and alsactl daemon is running:

```
# ps aux|grep alsactl
root       25033  0.0  0.0   5012  2880 ?        SNs  17:27   0:00 /usr/bin/alsactl -s -n 19 -c rdaemon
root       25077  0.0  0.0   8828  2196 pts/1    S+   17:30   0:00 grep alsactl
```

**Comment by perexg** [comment]
Yes, you can change the save period using the '-p' argument. 5 minutes is the default. If you reboot correctly, the `ExecStop=-/usr/sbin/alsactl -s kill save_and_quit` command from the alsa-state.service should be ran. So the mixer settings should be saved on shutdown.

Does the volume persist without pulseaudio ?

**Comment by Oscar65** [comment]
After deactivate pulseaudio, the volume persist after boot. I deactivate with:

```
$ mkdir -p $HOME/.config/systemd/user
$ systemctl --user mask pulseaudio.socket
```

I tested before to stop and start pulseaudio and every time I started pulseaudio, the volume changes.

Thanks a lot for your support!
