### ISSUE TITLE
Translation for alsa-utils

### ISSUE THREAD

**Issue by Porrumentzio** [alsa-project/alsa-utils#41]
I found the [po folder](https://github.com/alsa-project/alsa-utils/tree/master/po) but seems that there are not all the translations (I know there's a Spanish localization for example). 

Is it enough to translate the po files and PR them? Or is there any other procedure?

**Comment by perexg** [comment]
Hi, a PR is a good way to submit your translations. Thank you.

**Comment by Porrumentzio** [comment]
Does Alsa-Utils gettext support Unicode characters, such as →←↑↓?

They would be more internationally comprehensible and with less characters
