### ISSUE TITLE
arecord command stop when output file set /dev/null

### ISSUE THREAD

**Issue by garyfcg** [alsa-project/alsa-utils#48]
How to reproduce it?
1. Input the below command, then record go on 
arecord -r 96000 -c 4 -f S32_LE  1> /dev/null 

2. Wait for some minutes, it depended on system memory size.
For example,system memory had 2G, 
(2*1024*1024*1024)/(96k*4*32/8)=1400s

The results:
1. this command quit auto.

Expect:
1. This command should not be interrupted.

**Comment by dbaluta** [comment]
Can you try:

```
 arecord -r 96000 -c 4 -f S32_LE  /dev/null
```

**Comment by garyfcg** [comment]
Hi，
Thanks for your reply fastly.
It was the same error.
/dev/null: Resource temporarily unavailable

**Comment by garyfcg** [comment]
Hi Dbaluta,

Added some debugged information, find it exit on capture, if count <=0, the whole loop will break, so it can't be recorded.

I will submit one patch for fixing it.

 while (rest > 0 && recycle_capture_file == 0 && !in_aborting) {
                        size_t c = (rest <= (off64_t)chunk_bytes) ?
                                (size_t)rest : chunk_bytes;
                        size_t f = c * 8 / bits_per_frame;
                        if (pcm_read(audiobuf, f) != f) {
                                break;
                        }
                        if (write(fd, audiobuf, c) != c) {
                                perror(name);
                                prg_exit(EXIT_FAILURE);
                        }
                        count -= c;
                        rest -= c;
                        fdcount += c;

**Comment by garyfcg** [comment]
Hi Dbaluta,

I found this action form capture function. I think that it should be a normal action,  not a bug. Could you please kindly give your comment?

Code:
--- a/aplay/aplay.c
+++ b/aplay/aplay.c
@@ -2932,8 +2932,10 @@ static void capture(char *orig_name)

        /* get number of bytes to capture */
        count = calc_count();
       if (count == 0)
                count = LLONG_MAX;
        /* compute the number of bytes per file */
        max_file_size = max_file_time *
                snd_pcm_format_size(hwparams.format,
@@ -2981,7 +2983,7 @@ static void capture(char *orig_name)
                        }
                        filecount++;
                }
-
+               error(_("[%s--%d]--count=%ld\n"), __func__, __LINE__, count);
                rest = count;
                if (rest > fmt_rec_table[file_type].max_filesize)
                        rest = fmt_rec_table[file_type].max_filesize;
@@ -3007,6 +3009,10 @@ static void capture(char *orig_name)
                        count -= c;
                        rest -= c;
                        fdcount += c;
+
+                       if (count <= 0)
+                               error(_("[%s--%d]--count=%ld\n"), __func__, __LINE__, count);
+

Log:
arecord: capture:2986: [capture--2986]--count=2147483648
arecord: capture:3014: [capture--3014]--count=0
arecord: captur[ 2829.154010@0] aml_pdm_dai_trigger, cmd:0

**Comment by garyfcg** [comment]
arecord -r 96000 -c 4 -f S32_LE -t raw 1> /dev/null
Checked the count，it was not limited on time.


arecord: capture:2964: [capture--2964]--count=9223372036854775806

arecord: capture:2967: [capture--2967]--count=9223372036854775806

arecord: capture:2990: [capture--2990]--count=9223372036854775806

arecord: capture:2996: [capture--2996]--rest=9223372036854775806

arecord: capture:3000: [capture--3000]--count=9223372036854775806, rest=922337203685477580
