### ISSUE TITLE
Typo in 00main file?

### ISSUE THREAD

**Issue by bigon** [alsa-project/alsa-utils#52]
Hello,

Looking at the 00main file, I think I found [a typo](https://github.com/alsa-project/alsa-utils/blob/805d30b260d0f7f7c4453ef09e11f2c3f1b548d5/alsactl/init/00main#L39)

Shouldn't `GOTO="00_mainend"` be  `GOTO="00main_end"`

Edit: git blame says that the change is 12years old

**Comment by ahlinc** [comment]
It seems that a distro specific preinit and postinit configs is rare thing.

**Comment by perexg** [comment]
Fixed in 860b851639f1674ad003114acc4a6c15fa94ab6e . Thank you.
