### ISSUE TITLE
Miss mapping to unmute the middle speakers for Creative X-Fi with 20K1 chipset cards in analog-output.conf

### ISSUE THREAD

**Issue by deathxxx123** [alsa-project/alsa-utils#54]
Hi there. I want to report some bug, that is present from long time and i think that can be fixed now.
With any configuration that uses center/subwoofer, that center gets muted by default for Creative X-Fi with 20K1 chipset cards, but if you have other card, that will not happen, because of missing configuration for Center/Subwoofer in `analog-output.conf`.
The missing thing in `analog-output.conf` is:
```
[Element Center/LFE]
switch = mute
volume = merge
override-map.1 = center,lfe
```
You can see my issue and fix there:
https://github.com/gamer-os/gamer-os/issues/131

**Comment by perexg** [comment]
It's pulseaudio configuration. Report this here: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/

**Comment by deathxxx123** [comment]
Thank you!
