### ISSUE TITLE
aplay: playing mono audio file alteres pulseaudio default Master left or right volume level

### ISSUE THREAD

**Issue by maxmbed** [alsa-project/alsa-utils#55]
I am encountering an unexpected behaviour with pulse audio master volume in my application. 

### Description

If I set for example left channel to 100% and right channel 0%, and play mono audio file (i.e. audio file with 1 channel only), then I would expect to hear only the audio file on left channel.

The actual behaviour in the example of above is when playing the audio file, the Master volume right channel will be automatically adjusted to 50%. If play again it increases to 75% and so on. 

This issue happens also with other R/L volume level, the case of above is just an example.

**Important to note the case does not happen with stereo audio file** where audio sounds on left only channel as we can expected.

### Steps to repeat issue:

(a) Set mixer Lch to 100%, Rch to 0%
```
$ amixer -D default sset Master 65535,0
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65535 [100%] [on]
  Front Right: Playback 0 [0%] [on]
```

(b) Play mono audio file
```
$ aplay -D default ringtone.wav
Playing WAVE 'ringtone.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
```

### Request
(1) Is it by design expected ? 
(2) Is there a way to prevent this phenomenon (command option) ?

**Comment by perexg** [comment]
I cannot reproduce this behaviour here. It's probably a PA issue. You may report this as PA bug - https://gitlab.freedesktop.org/pulseaudio/pulseaudio .

<pre>
$ amixer set Master 100%,0
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [on]
  Front Right: Playback 0 [0%] [on]
$ aplay -D default -r 44100 -f S16_LE -d 5 /dev/zero
Playing raw data '/dev/zero' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
$ amixer get Master
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [on]
  Front Right: Playback 0 [0%] [on]
</pre>

**Comment by maxmbed** [comment]
Indeed, playing straight to pcm device instead of pulseaudio does not change volume level. 
Thanks.
