### ISSUE TITLE
"aplay -D oss -l" still reads sound cards through ALSA, not OSS

### ISSUE THREAD

**Issue by yurivict** [alsa-project/alsa-utils#56]
I don't have any ALSA devices, only OSS devices.

When the OSS PCM is selected ```aplay``` still tries to read ALSA devices:
```
$ /usr/bin/aplay -D oss -l
aplay: device_list:272: no soundcards found...
```

```
$ /usr/bin/aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
oss
    Open Sound System
```

But ```/usr/bin/aplay x.wav``` plays it through the OSS card.

aplay should list OSS cards when -D is selected.
The ALSA interface should also list OSS cards when no ALSA cards are present but it doesn't.

alsa-lib-1.1.8
alsa-plugins-oss-1.1.6
alsa-utils-1.1.8

**Comment by perexg** [comment]
I don't follow this request. We list only ALSA cards. The emulated CTL / PCM devices are not connected to any ALSA card. It's like null PCM device which is not listed as a card, too.
