### ISSUE TITLE
Bad vumeter data in aplay/arecord

### ISSUE THREAD

**Issue by SuitableUsername** [alsa-project/alsa-utils#57]
In aplay.c the wrong count is passed to compute_max_peak(). Instead of "r * hwparams.channels" it should be "r * bits_per_frame / 8".

Also, the vumeter should really show an overall peak level percentage because the transitory 1/8 second one has very little value.

**Comment by perexg** [comment]
Thanks. Fixed in 246e132b802ba83a902b3b20f654151ee810850c .

It's really simple linear vumeter. If you like to see meter history, use '-vvv' argument.
