### ISSUE TITLE
Can't aplay/arecord simultaneously inside and outside of linux container

### ISSUE THREAD

**Issue by fearless-fan** [alsa-project/alsa-utils#62]
Hi,
I run into a problem that can't aplay/arecord simultaneously inside and outside of linux container. 

Steps to reproduce:
1. go into container's shell and exec a record command. 

~ # lxc-attach -n Default -P /tmp/run/lxc
/ # arecord -d 60 /tmp/test.wav &
/ # Recording WAVE '/tmp/test.wav' : Unsigned 8 bit, Rate 8000 Hz, Mono
/ # ps
PID   USER     TIME   COMMAND
      1 root       0:00 /sbin/init
      3 root       0:00 /bin/sh
1519 root       0:00 arecord -d 60 /tmp/test.wav
1520 root       0:00 /bin/ash
1521 root       0:00 ps

2. exit and exec another record command outside of container

/ # exit
~ # arecord -d 60 /tmp/test.wav &
~ # ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
arecord: main:830: audio open error: Device or resource busy

[1]+  Done(1)                    arecord -d 60 /tmp/test.wav

3. playback has same problem as below

ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
aplay: main:830: audio open error: Device or resource busy

Expect:
It should be allowed to play/record simultaneously inside and outside of linux container.

Here's my asound.conf:

~ # cat etc/asound.conf
pcm.asymed {
    type asym
    playback.pcm "dmix:0,0"
    capture.pcm "dsnoop:0,0"
}

pcm.!default {
    type plug
    slave.pcm "asymed"
}

ctl.!default {
        type hw
        card 0
}

Is there anyone has experience of how to address it? Thank you.

**Comment by takaswie** [comment]
Hi,

The `dmix` and `dsnoop` plugins comes from alsa-lib. They uses System V Shared Memory Segment (see `$ man 7 sysvipc`) to multiplex PCM frames from several processes to hardware, or to delivery PCM frames from hardware to several processes.

In your case, outside of LXC container, processes attempt to use `dmix` and `dsnoop` plugins to access the Shared Memory Segment registered by the process inside LXC container. Usually, the case needs any help of system container manager so that the processes can access the Shared Memory Segment.

Would you investigate this kind of configuration and try it to your container?

**Comment by fearless-fan** [comment]
Hi takaswie,
Thank you for your explanation.
I'm trying to find out if there's any kind of configurations of lxc which control Shared Memory Segment. But my colleague told me that lxc is IPC isolated. So it seems there's no solution of my problem.

**Comment by takaswie** [comment]
> I'm trying to find out if there's any kind of configurations of lxc which control Shared Memory Segment. But my colleague told me that lxc is IPC isolated. So it seems there's no solution of my problem.

Essentially, the idea of `container` is based on kernel functionalities called as `namespace`. One of the functionalities is `IPC namespace`. It means that any shared object in System V fashion is isolated between the set of processes in each container. Therefore you need some additional configurations to your container itself or container manager.

According to manual of `lxc-start`[1], the command has `--share-ipc` option to share IPC namespace according to name. This looks to work in your case, however it's not for the resource on host (outside of container) and unavailable for your case.

If accessing to resources on host, the container should have priviledge. However I don't know how to make it in LXC v1.0...

For your information, `snd_pcm_direct_shm_create_or_connect()`[2] is called by dmix or dsnoop plugins. This function judges whether the process is first one to access to the Shared Memory Segment. If judged as first one, then the process is going to open ALSA PCM character device. In your case, any process outside of container is judged as first one, however it's not actually. EBUSY comes from open system call to the character device which is already used in the process in container.

[1] https://linuxcontainers.org/lxc/manpages//man1/lxc-start.1.html
[2] https://github.com/alsa-project/alsa-lib/blob/master/src/pcm/pcm_direct.c#L59

**Comment by fearless-fan** [comment]
Hi takaswie,

Many thanks for your information. 

Actually, I have a case of let two applications record/play simultaneously(one is in container). I will try to find if any solution of 'accessing the resource on host'. Before getting the answer, I think I can only move another application into container then it can share Shared Memory Segment with previous one.
