### ISSUE TITLE
How to set channel balance in amixer?

### ISSUE THREAD

**Issue by quantum-booty** [alsa-project/alsa-utils#73]
When I change volumn using keyboard media keys, the left and right channel becomes imbalanced. 
![image](https://user-images.githubusercontent.com/28958399/101188833-23befc00-364e-11eb-8816-efd94b9514d4.png)
I currently have this mapping in i3, I would like to add command to balance the channels after I change the volumn.
bindsym XF86AudioRaiseVolume exec --no-startup-id "amixer set Master '5%+,5%+'"

**Comment by perexg** [comment]
Workaround: use command `flock /tmp/amixer.lock amixer set Master 5%+`.
