### ISSUE TITLE
[Feature request][alsactl] Allow -g/--ignore to be used with init command

### ISSUE THREAD

**Issue by MichaIng** [alsa-project/alsa-utils#75]
It would be great if the `-g`/`--ignore` flag would have an effect on the `init` command as well, so that `alsactl -g init` does not print and exit with an error, if no sound cards have been found.

Since it can be checked for attached sound cards on Linux easily via /proc or sysfs, this is of minor importance, and probably there is a reason why it is as it is. In this case, probably the `--help` output could be extended by this info, which is currently only present in the man page. Reading the `--help` only, one (or at least me) would not guess that this flag is ignored by the `init` command.

**Comment by perexg** [comment]
Added to 65453da000a03910f47010795bef45b4ad555f9f . Thank you for your request.

**Comment by MichaIng** [comment]
Awesome, many thanks! I just opened a PR to align the manpage: #80
