### ISSUE TITLE
man: alsaloop man page error

### ISSUE THREAD

**Issue by nootc** [alsa-project/alsa-utils#82]
There is a small typo in the alsaloop man page:
https://github.com/alsa-project/alsa-utils/blob/c9e9a79c6cfef3212bdb5f9be4f6ea1d2a5e8670/alsaloop/alsaloop.1#L76-L86
"-c" is used for both "channels" and "rate". Thankfully, the source thinks otherwise and "-r" is used for "rate".

**Comment by perexg** [comment]
Fixed in 0369271aace516647ae7a3d4d365ce2a9be6b5d0 .
