### ISSUE TITLE
Setting volume of headphones seems to apply to Speakers as well

### ISSUE THREAD

**Issue by roboknight** [alsa-project/alsa-utils#87]
When using amixer in the following way:

amixer -c 1 set Headphone 0% mute

I receive the following partial output from scontents:

Simple mixer control 'Headphone',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 0 [0%] [-65.25dB] [off]
  Front Right: Playback 0 [0%] [-65.25dB] [off]
Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 87 [100%] [0.00dB] [on]
  Front Right: Playback 87 [100%] [0.00dB] [on]

which looks good.  However, it appears that the volume is applied across both the Headphone control and Speaker control (or maybe even just the Master volume) as there is no output from the speakers after this even though it would appear they should have full volume and are not muted.

I am using the Ubuntu Groovy Gorilla update, so Linux kernel 5.11.  The default installation uses pulseaudio, but I've switched things to pipewire and both cause the same issue presumably because both use ALSA.  I started here because amixer seems to at least allow me to identify the problem.  When I change the Volume for the Headphones to 100% using the following:

amixer -c 1 set Headphone 100% mute

the audio from the speakers is then fine.  amixer appears to be showing the correct information (as per above) according to the audio, but the Headphone volume seems to be applying to the Speakers as well.  Maybe someone can point me in a direction that I can find a solution to this, as it would appear that anytime headphones are plugged in, removing the headphones causes the same situation: no sound.  I suspect amixer is working fine, but wherever the volume from amixer is applied, it does not appear to be set appropriately.

**Comment by perexg** [comment]
It looks like a kernel driver issue.

**Comment by perexg** [comment]
We cannot do much in the user space. Those controls are created by the driver, thus the fix should be in the driver. I suggest to create bug at https://bugzilla.kernel.org/ .

**Comment by roboknight** [comment]
Thanks for tracking that down.  I wasn't sure where to go after this.  I'll try there.
