### ISSUE TITLE
axfer: FTBFS of axfer with glibc-2.11 or before due to missing definition of POLLRDNORM

### ISSUE THREAD

**Issue by takaswie** [alsa-project/alsa-utils#9]
Reported by Jay Foster in alsa-devel list.
http://mailman.alsa-project.org/pipermail/alsa-devel/2019-January/144024.html

The v1.1.8 release brings FTBFS of axfer in his legacy toolchain (glibc v2.9)
for arm platform, due to missing definition `POLLRDNORM` and the others, used in
`axfer/waiter-select.c`. An option of  `-D_GNU_SOURCE` for CFLAGS can suppress
the issue. With glibc v2.22, no issues.

During development period of axfer, this issue has never been got. More recent
version of glibc (v2.28) was used and the macro is available without any explicit
options.

**Comment by takaswie** [comment]
In glibc-2.28, the macro is enabled with `__USE_XOPEN2K8` flag of glibc,
therefore it seems to be added officially to XPG-7 (IEEE 1003-1:2008). As
long as I investigated, XPG-7 is a default behaviour in glibc 2.12 or later. I
pick up some releases of glibc related for this issue.

* glibc-2.9: 2008/11/13
  * reported version
* glibc-2.10: 2009/5/9
  * add '__USE_XOPEN2k8' for XPG-7/POSIX-2008
* glibc-2.12: 2010/5/3
  * POLLRDNORM is available with __USE_XOPEN2K8
  * XPG-7/POSIX-2008 is a default behaviour
* glibc-2.19: 2014/2/7
  * add '_DEFAULT_SOURCE' macro
* glibc-2.20: 2014/9/7
  * obsolete '_BSD_SOURCE' and '_SYSV_SOURCE' macros
* glibc-2.28: 2018/8/1
  * in my development environment

As long as built with glibc-2.11 or before, '_GNU_SOURCE' option is required for current axfer.

**Comment by tiwai** [comment]
As Jaroslav already pointed out on ML, there are a few different ways to fix this.

I'd fix up just by #ifdef and define local ones, but feel free to pick up your favorite one.  This bug is an easy and trivial one, after all.

**Comment by takaswie** [comment]
> This bug is an easy and trivial one, after all.

Yep. The bug is not critical with recent toolchains and the most of users never get bothered. I filed this issue here to handle later when I can keep enough time for it.

@perexg would I request you to add me to a group of developer in this project and grant permission to handle label feature?

**Comment by takaswie** [comment]
Fix committed at 257be19c47e6 ("axfer: allow to be compiled with glibc-2.11 or former").
