### ISSUE TITLE
aconnect doesn't connect by name if the device name starts with a number

### ISSUE THREAD

**Issue by abreubacelar** [alsa-project/alsa-utils#90]
Hello, i don't know if this is the right place, if it is not please tell me where to report the issue, but i had this problem:

i have this devices with aconnect -i :

client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 16: 'FCA610' [type=kernel,card=0]
    0 'FCA610 MIDI 1   '
client 20: '12Step' [type=kernel,card=1]
    0 '12Step MIDI 1   '
    1 '12Step MIDI 2   '

the last one, 12Step, only connects if i use the 20:0 notation, 12Step:0 doesn't works, my error message is in portuguese, i get this:

if i do 

aconnect 12Step:0 "Pure Data":0

i get

Conexão falhou (Argumento inválido)

(connection failed, (invalid argument) )

if i try aconnect 20:0 "Pure Data":0 it works

if i try "12Step", or '12Step', they doesn't work either

i'm on ubuntu 20.04.2

**Comment by perexg** [comment]
I tried to fix this in alsa-lib - https://github.com/alsa-project/alsa-lib/commit/c8f608d67463b814f2c077c3cdae5663f3574f12 .
