### ISSUE TITLE
aplay change to use 16-bit samples by default is not backwards compatible and is not documented

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [alsa-project/alsa-utils#96]
The change introduced in https://github.com/alsa-project/alsa-utils/commit/0c5948e98a6a8535c89b7bcab13017d7732181c6 breaks a lot of scripts and other programs I have which invoke `aplay` and expect the default sample format to be U8. While I think it's somewhat reasonable to make this change given that U8 is a rather low quality sample format, it's worth acknowledging that aplay has had this behavior for a very long time and many people probably don't expect it to change.

Given that the commit log seems to only talk about the case of `arecord`, I wonder if we could reach a compromise and keep the format as U8 for `aplay` and switch it for `arecord`, since users are unlikely to complain about poor sound quality when *playing raw audio* (surely they would take the time to get the sample format set up correctly before attempting to play raw audio).

Also, the man page has not been updated to reflect this change and still says that U8 is the default.

**Comment by pavhofman** [comment]
IMO a script which does not explicitly specify sample format and assumes a tool default value is buggy and should be fixed.

I would prefer if aplay and arecord used the same default values (be they U8 or S16_LE)

**Comment by nwoeanhinnogaehr** [comment]
Relying on default values is pretty essential to prevent every invocation from being absurdly verbose. For example you wouldn't run `gcc foo.c` and expect it to optimize with `-O3` by default, or worse to pass `-nostdlib` by default. The default sample format is listed in the man page and has been unchanged for at least as long as this repo has existed (since 1998).

Perhaps it makes sense to change the default for recording wav files for the reasons outlined in the commit log, but I don't see why raw audio playback/recording should be affected. The commit in question is specifically talking about recording wav files. Yet it also changes the default for playing and recording raw audio (and voc and au files), with seemingly no consideration about those cases.

**Comment by perexg** [comment]
For the second though, I take your arguments and trying to resolve the issue with a warning in https://github.com/alsa-project/alsa-utils/commit/fc7500c3c7a7d6bfb975a87e23b7544a84da3186 . It seems like a good compromise.
